# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
 
theme: alembic-jekyll-theme

# 3. Gem settings
paginate: 1 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: SimonCarrignon # jekyll-seo-tag > Owners twitter username
author: SimonCarrignon # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Simon Carrignon # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)

# 4. Jekyll settings
sass:
    style: :compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Barcelona # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "more" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "/assets/unnamed2.png"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: home # Default layout
      feature_image: "/assets/unnamed2.png"
      text-color: "white" 
      color: "white" 
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Satellite Session @ CCS 2018 Thessaloniki" # Site name or title, also used in jekyll-seo-tag
logo: "/logo.png" # Site logo, also used in jekyll-seo-tag
description: "Sattellite Session at the Conference on Complex System: Evolution of Cultural Complexity III" # Site description and default description, also used in jekyll-seo-tag
url: "http://ccs2018.web.auth.gr/" # Site url, also used in jekyll-seo-tag
repo: ""
email: "simon.carrignon@bsc.es"
disqus: "alembic-1"
avatarurl: "" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Program: /program/
  Speakers: /speakers/
  Committees: /committees/
  Sponsors: /sponsors/
  Call for Abstract: /call/

navigation_footer:
    BSC : 
        url: http://bsc.es
        logo: /assets/logo/bsc.png
    IBE : 
        url: https://www.ibe.upf-csic.es/ 
        logo: /assets/logo/ibe_logo.png
    AEI : 
        logo: /assets/logo/aei_logo.png
    EPNet : 
        url: http://www.roman-ep.net
        logo: /assets/logo/epnet.png
    ERC : 
        url: https://erc.europa.eu/
        logo: /assets/logo/erc-white.svg

    EU : 
        url: https://europa.eu/
        logo: /assets/logo/europe.jpg


social_links:
  LinkedIn: 
  Google+: 
  GitHub: 
  link: 

sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  Designer News: "#2D72D9"
  Email: ""
